In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [2]:
# Load CPU Datasets
cpu1 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\host_metrics_host1.csv"
)
server1_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\ilo_server_metrics_iloserver1.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

cpu2 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\host_metrics_host2.csv"
)
server2_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\ilo_server_metrics_iloserver2.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

cpu3 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\host_metrics_host3.csv"
)
server3_resource = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\Datacenter Datas\Datacenter Datas\SERVER WISE DATA\ilo_server_metrics_iloserver3.csv",
    usecols=[
        "ts",
        "ilo_server_id",
        "inlet_temp_c",
        "cpu_temp_c",
        "processor_count"
    ]
)

In [3]:
# inspect CPU Datasets
print("CPU1")
display(cpu1.head())
print("server1_resource")
display(server1_resource.head())

print("CPU2")
display(cpu2.head())
print("server2_resource")
display(server2_resource.head())

print("CPU3")
display(cpu3.head())
print("server3_resource")
display(server3_resource.head())

CPU1

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,status
0,1,2026-04-02 12:22:07.517+00,1,4.0,74.0,0.220,Normal
1,4,2026-04-02 12:24:02.882+00,1,5.0,74.0,0.220,Normal
2,7,2026-04-02 12:26:01.7+00,1,4.0,74.0,0.221,Normal
3,10,2026-04-02 12:28:01.845+00,1,7.0,74.0,0.220,Normal
4,13,2026-04-02 12:30:02.091+00,1,5.0,74.0,0.221,Normal

server1_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-04-02 12:22:07.517+00,1,20,38,2
1,2026-04-02 12:24:02.882+00,1,20,38,2
2,2026-04-02 12:26:01.7+00,1,21,38,2
3,2026-04-02 12:28:01.845+00,1,20,38,2
4,2026-04-02 12:30:02.091+00,1,20,38,2

CPU2

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,status
0,2,2026-04-02 12:22:07.517+00,2,17.0,70.0,0.245,Normal
1,5,2026-04-02 12:24:02.882+00,2,16.0,70.0,0.263,Normal
2,8,2026-04-02 12:26:01.7+00,2,15.0,70.0,0.256,Normal
3,11,2026-04-02 12:28:01.845+00,2,16.0,70.0,0.251,Normal
4,14,2026-04-02 12:30:02.091+00,2,16.0,70.0,0.260,Normal

server2_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-04-02 12:22:07.517+00,2,20,43,2
1,2026-04-02 12:24:02.882+00,2,20,44,2
2,2026-04-02 12:26:01.7+00,2,21,44,2
3,2026-04-02 12:28:01.845+00,2,20,44,2
4,2026-04-02 12:30:02.091+00,2,20,45,2

CPU3

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,status
0,3,2026-04-02 12:22:07.517+00,3,28.0,27.0,0.253,Normal
1,6,2026-04-02 12:24:02.882+00,3,28.0,27.0,0.252,Normal
2,9,2026-04-02 12:26:01.7+00,3,27.0,27.0,0.252,Normal
3,12,2026-04-02 12:28:01.845+00,3,27.0,27.0,0.254,Normal
4,15,2026-04-02 12:30:02.091+00,3,28.0,27.0,0.240,Normal

server3_resource

,ts,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2026-04-02 12:22:07.517+00,3,18,28,2
1,2026-04-02 12:24:02.882+00,3,18,48,2
2,2026-04-02 12:26:01.7+00,3,19,49,2
3,2026-04-02 12:28:01.845+00,3,18,48,2
4,2026-04-02 12:30:02.091+00,3,18,49,2

In [4]:
# Check column names
print(cpu1.columns)
print(cpu2.columns)
print(cpu3.columns)
print(server1_resource.columns)
print(server2_resource.columns)
print(server3_resource.columns)

Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'status'],
      dtype='object')
Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'status'],
      dtype='object')
Index(['id', 'ts', 'host_id', 'cpu_usage_pct', 'memory_usage_pct', 'power_kw',
       'status'],
      dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')
Index(['ts', 'ilo_server_id', 'inlet_temp_c', 'cpu_temp_c', 'processor_count'], dtype='object')

In [5]:
# convert timestamp columns
cpu1["ts"] = pd.to_datetime(
    cpu1["ts"],
    format="mixed",
    utc=True
)

cpu2["ts"] = pd.to_datetime(
    cpu2["ts"],
    format="mixed",
    utc=True
)

cpu3["ts"] = pd.to_datetime(
    cpu3["ts"],
    format="mixed",
    utc=True
)

server1_resource["ts"] = pd.to_datetime(
    server1_resource["ts"],
    format="mixed",
    utc=True
)

server2_resource["ts"] = pd.to_datetime(
    server2_resource["ts"],
    format="mixed",
    utc=True
)

server3_resource["ts"] = pd.to_datetime(
    server3_resource["ts"],
    format="mixed",
    utc=True
)

In [6]:
# verify dataset size
print(cpu1.shape)
print(cpu2.shape)
print(cpu3.shape)

print("\nTotal rows expected:")
print(len(cpu1) + len(cpu2) + len(cpu3))

(24762, 7)
(24762, 7)
(24762, 7)

Total rows expected:
74286

In [7]:
HOST_MAP = {
    1: "10.10.10.65",
    2: "10.10.10.150",
    3: "10.10.10.2"
}
cpu1["hostName"] = cpu1["host_id"].map(HOST_MAP)

cpu2["hostName"] = cpu2["host_id"].map(HOST_MAP)

cpu3["hostName"] = cpu3["host_id"].map(HOST_MAP)

In [8]:
# combining all CPU Datasets
server1 = pd.merge(
    cpu1,
    server1_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

server2 = pd.merge(
    cpu2,
    server2_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

server3 = pd.merge(
    cpu3,
    server3_resource,
    left_on=["ts", "host_id"],
    right_on=["ts", "ilo_server_id"],
    how="inner"
)

print(server1.shape)
print(server2.shape)
print(server3.shape)

(24761, 12)
(24762, 12)
(24762, 12)

In [9]:
cpu_master = pd.concat(
    [server1, server2, server3],
    ignore_index=True
)

HOST_MAP = {
    1: "10.10.10.65",
    2: "10.10.10.150",
    3: "10.10.10.2"
}

cpu_master["hostName"] = (
    cpu_master["host_id"]
    .map(HOST_MAP)
)
cpu_master.shape

(74285, 12)

In [10]:
# inspect combined dataset
cpu_master.head()
# verify unique hosts
cpu_master["hostName"].unique()

array(['10.10.10.65', '10.10.10.150', '10.10.10.2'], dtype=object)

In [11]:
# CPU Dataset information
cpu_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74285 entries, 0 to 74284
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                74285 non-null  int64
 1   ts                74285 non-null  datetime64[ns, UTC]
 2   host_id           74285 non-null  int64
 3   cpu_usage_pct     74285 non-null  float64
 4   memory_usage_pct  74285 non-null  float64
 5   power_kw          74285 non-null  float64
 6   status            74285 non-null  object
 7   hostName          74285 non-null  object
 8   ilo_server_id     74285 non-null  int64
 9   inlet_temp_c      74285 non-null  int64
 10  cpu_temp_c        74285 non-null  int64
 11  processor_count   74285 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(3), int64(6), object(2)
memory usage: 6.8+ MB

In [12]:
# missing values check
cpu_master.isnull().sum()

id                  0
ts                  0
host_id             0
cpu_usage_pct       0
memory_usage_pct    0
power_kw            0
status              0
hostName            0
ilo_server_id       0
inlet_temp_c        0
cpu_temp_c          0
processor_count     0
dtype: int64

In [13]:
# duplicate check
cpu_master.duplicated().sum()

np.int64(0)

In [15]:
# timestamp range
print("Earliest Timestamp:")
print(cpu_master["ts"].min())

print("\nLatest Timestamp:")
print(cpu_master["ts"].max())

Earliest Timestamp:
2026-04-02 12:22:07.517000+00:00

Latest Timestamp:
2026-06-11 04:26:39.251000+00:00

In [17]:
# Sort dataset
cpu_master = cpu_master.sort_values(
    ["hostName", "ts"]
)

In [18]:
# reset index
cpu_master = cpu_master.reset_index(
    drop=True
)

In [19]:
# save processed dataset
Path("../data/Processed").mkdir(
    parents=True,
    exist_ok=True
)
cpu_master.to_csv(
    "../data/Processed/cpu_master.csv",
    index=False
)

In [20]:
print(cpu_master.shape)

cpu_master.head()

(74285, 12)

,id,ts,host_id,cpu_usage_pct,memory_usage_pct,power_kw,status,hostName,ilo_server_id,inlet_temp_c,cpu_temp_c,processor_count
0,2,2026-04-02 12:22:07.517000+00:00,2,17.0,70.0,0.245,Normal,10.10.10.150,2,20,43,2
1,5,2026-04-02 12:24:02.882000+00:00,2,16.0,70.0,0.263,Normal,10.10.10.150,2,20,44,2
2,8,2026-04-02 12:26:01.700000+00:00,2,15.0,70.0,0.256,Normal,10.10.10.150,2,21,44,2
3,11,2026-04-02 12:28:01.845000+00:00,2,16.0,70.0,0.251,Normal,10.10.10.150,2,20,44,2
4,14,2026-04-02 12:30:02.091000+00:00,2,16.0,70.0,0.260,Normal,10.10.10.150,2,20,45,2